name: rteqcorrscan-test
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy>=1.12
  - matplotlib>=1.3.0
  - scipy>=0.18
  - bokeh
  - obspy>=1.0.3
  - h5py
  - pyyaml
  - pyproj>2.1
  - EQcorrscan>=0.4.3
  - urllib3>=1.24.3
  - obsplus>=0.1.0
  - pytest>=2.0.0
  - pytest-cov
  - pytest-pep8
  - pytest-xdist
  - pytest-rerunfailures
  - pytest-mpl
  - codecov
