name: rteqcorrscan-test
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy>=1.22.2,<2.0  # Obsplus uses np.NaN which was removed in numpy 2.0
  - matplotlib>=1.3.0
  - scipy>=1.10.0rc1
  - bokeh
  - obspy>=1.0.3
  - h5py
  - pyyaml
  - pyproj>2.1
  - tqdm
  - pygmt
  - EQcorrscan>=0.5.2
  - urllib3>=1.24.3
  - obsplus>=0.1.1
  - pytest>=2.0.0
  - pytest-cov
  - pytest-pep8
  - pytest-xdist
  - pytest-rerunfailures
  - pytest-mpl
  - codecov
  - notifiers
  - pympler
  - psutil
  - geographiclib
  - statsmodels
