#!/usr/bin/env python3
"""
Build a template database based on configuration parameters.

Author
    Calum J Chamberlain
License
    GPL v3.0
"""

import logging
import faulthandler

faulthandler.enable()

from obspy import UTCDateTime
from concurrent.futures import ProcessPoolExecutor

from rt_eqcorrscan.config import read_config
from rt_eqcorrscan.database import TemplateBank


Logger = logging.getLogger(__name__)


def run(
    starttime: UTCDateTime,
    endtime: UTCDateTime,
    rebuild: bool = True,
    max_workers: int = None,
    **kwargs
):
    config = read_config(config_file=kwargs.get("config_file", None))
    debug = kwargs.get("debug", False)
    if debug:
        config.log_level = "DEBUG"
        print("Using the following configuration:\n{0}".format(config))
    config.setup_logging()
    Logger.debug("Running in debug mode - expect lots of output!")

    client = config.rt_match_filter.get_client()

    template_bank = TemplateBank(
        config.database_manager.event_path,
        event_name_structure=config.database_manager.event_name_structure,
        event_format=config.database_manager.event_format,
        path_structure=config.database_manager.path_structure,
        event_ext=config.database_manager.event_ext,
        executor=ProcessPoolExecutor(max_workers=max_workers))

    catalog = client.get_events(
        starttime=starttime, endtime=endtime,
        **config.reactor.catalog_lookup_kwargs)
    Logger.info("Will make templates for {0} events".format(len(catalog)))

    template_bank.make_templates(
        catalog=catalog, rebuild=rebuild, client=client, **config.template)


if __name__ == "__main__":
    import argparse

    kwargs = {}
    parser = argparse.ArgumentParser(
        description="Build a TemplateBank; by default, if the "
                    "TemplateBank exists, only new templates will be added. "
                    "Use '-r' flag to enforce re-construction of templates "
                    "already in the TemplateBank")
    parser.add_argument(
        "--config", "-c", type=str, help="Path to configuration file",
        required=False)
    parser.add_argument(
        "--debug", action="store_true", help="Flag to set log level to debug")
    parser.add_argument(
        "-s", "--starttime", type=str,
        help="Starttime parsable by obspy's UTCDateTime to begin database from")
    parser.add_argument(
        "-e", "--endtime", type=str,
        help="Endtime parsable by obspy's UTCDateTime to end database at")
    parser.add_argument(
        "-r", "--rebuild", action="store_true",
        help="Force templates already in the database to be re-constructed")
    parser.add_argument(
        "-n", "--max-workers", type=int, default=None,
        help="Maximum workers for ProcessPoolExecutor, defaults to the number "
             "of cores on the machine")

    args = parser.parse_args()

    try:
        starttime = UTCDateTime(args.starttime)
    except Exception as e:
        Logger.error(e)
        raise NotImplementedError(
            f"Could not parse {args.starttime} to UTCDateTime")

    try:
        endtime = UTCDateTime(args.endtime)
    except Exception as e:
        Logger.error(e)
        raise NotImplementedError(
            f"Could not parse {args.endtime} to UTCDateTime")

    kwargs.update({"debug": args.debug, "config_file": args.config})
    run(starttime=starttime, endtime=endtime, rebuild=args.rebuild,
        max_workers=args.max_workers, **kwargs)
